/**
 * Built-in Professional Starter Templates for ID & Service Card Designer
 * Pre-configured dual-card layouts on a single A6 page (Front on top, Back underneath).
 * 
 * Standard CR-80 card dimension: 85.6 mm × 54.0 mm with 3.18 mm rounded corners.
 * Upper Zone: 105 mm × 74 mm (Front Card centered at x: 9.7, y: 10.0)
 * Lower Zone: 105 mm × 74 mm (Back Card centered at x: 9.7, y: 10.0)
 */

import { CardDesignerProject, CardObject } from "./types";
import { generateBarcodeDataUrl } from "./barcodeGenerator";

export function createBlankProject(
  name: string = "Untitled Card Design",
  orientation: "portrait" | "landscape" = "portrait"
): CardDesignerProject {
  const isPortrait = orientation === "portrait";
  // A6 sheet: 105 x 148 mm in portrait, 148 x 105 mm in landscape
  const pageWidthMm = isPortrait ? 105 : 148;
  const pageHeightMm = isPortrait ? 148 : 105;

  // In portrait A6: sheet is 105mm wide x 148mm high.
  // Upper half zone (front): 105mm wide x 74mm high at (0, 0)
  // Lower half zone (back): 105mm wide x 74mm high at (0, 74)
  const cardWidthMm = 105;
  const cardHeightMm = 74;

  const frontPosMm = isPortrait
    ? { x: 0, y: 0 }
    : { x: 5, y: Math.max(0, (pageHeightMm - cardHeightMm) / 2) };

  const backPosMm = isPortrait
    ? { x: 0, y: 74 }
    : { x: 5 + cardWidthMm + 8, y: Math.max(0, (pageHeightMm - cardHeightMm) / 2) };

  return {
    id: `card-proj-${Date.now()}`,
    name,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    pageFormat: "A6",
    orientation,
    pageWidthMm,
    pageHeightMm,
    cardWidthMm,
    cardHeightMm,
    trueCardWidthMm: 85.6,
    trueCardHeightMm: 54.0,
    trueCardOrientation: "landscape",
    cardPreset: "id1_cr80",
    showCardBoundary: true,
    showBleedShading: true,
    cardCornerRadiusMm: 3.18,
    frontPosMm,
    backPosMm,
    safeAreaMarginMm: 3,
    bleedMarginMm: 2,
    cuttingGuides: true,
    showBleed: false,
    showSafeArea: true,
    showRulers: true,
    showGrid: false,
    snapToGrid: true,
    snapToObjects: true,
    snapToCardBoundary: true,
    gridSizeMm: 2,
    guides: {
      horizontal: [10, 64, 84, 138],
      vertical: [9.7, 95.3],
    },
    front: {
      background: {
        type: "solid",
        color1: "#ffffff",
      },
      objects: [],
    },
    back: {
      background: {
        type: "solid",
        color1: "#ffffff",
      },
      objects: [],
    },
  };
}

export function createCorporateEmployeeTemplate(): CardDesignerProject {
  const project = createBlankProject("Corporate Employee Badge", "portrait");
  const barcodeData = generateBarcodeDataUrl("EMP-84920-TITAN", "code128", { height: 40 });

  // Front Objects (Standard CR-80 85.6 × 54.0 mm centered in 105 × 74 mm zone: x: 9.7 to 95.3, y: 10.0 to 64.0)
  const frontObjects: CardObject[] = [
    // Header Banner
    {
      id: "f-banner-bg",
      name: "Header Banner",
      type: "shape",
      targetSide: "front",
      x: 9.7,
      y: 10,
      width: 85.6,
      height: 12,
      rotation: 0,
      opacity: 1,
      zIndex: 1,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      shapeType: "rect",
      fillColor: "#0f172a", // Deep Navy
      strokeWidth: 0,
    },
    {
      id: "f-company-name",
      name: "Company Name",
      type: "text",
      targetSide: "front",
      x: 12,
      y: 11.5,
      width: 81,
      height: 5,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "TITAN GLOBAL INDUSTRIES",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 9.5,
      fontWeight: "700",
      textAlign: "center",
      letterSpacing: 1,
      textColor: "#38bdf8", // Sky blue
      dynamicFieldKey: "companyName",
    },
    {
      id: "f-company-subtitle",
      name: "Company Subtitle",
      type: "text",
      targetSide: "front",
      x: 12,
      y: 16.5,
      width: 81,
      height: 4,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "AUTHORISED IDENTITY & ACCESS PASS",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 5.5,
      fontWeight: "600",
      textAlign: "center",
      letterSpacing: 0.5,
      textColor: "#94a3b8",
    },
    // Accent Stripe
    {
      id: "f-accent-stripe",
      name: "Accent Stripe",
      type: "shape",
      targetSide: "front",
      x: 9.7,
      y: 22,
      width: 85.6,
      height: 1,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      shapeType: "rect",
      fillColor: "#0284c7", // Sky 600
      strokeWidth: 0,
    },
    // Photo Placeholder Box
    {
      id: "f-photo-box",
      name: "Employee Photo Frame",
      type: "shape",
      targetSide: "front",
      x: 13,
      y: 25,
      width: 22,
      height: 27,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: true,
      flipX: false,
      flipY: false,
      shapeType: "rounded-rect",
      cornerRadius: 2,
      fillColor: "#f1f5f9",
      strokeColor: "#cbd5e1",
      strokeWidth: 0.5,
    },
    {
      id: "f-photo-text",
      name: "Photo Placeholder Text",
      type: "text",
      targetSide: "front",
      x: 13,
      y: 36,
      width: 22,
      height: 5,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "ID PHOTO",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 6,
      fontWeight: "700",
      textAlign: "center",
      textColor: "#94a3b8",
    },
    // Employee Name
    {
      id: "f-emp-name",
      name: "Employee Full Name",
      type: "text",
      targetSide: "front",
      x: 38,
      y: 24.5,
      width: 55,
      height: 5.5,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "ALEXANDER M. HAYES",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 10,
      fontWeight: "800",
      textAlign: "left",
      textColor: "#0f172a",
      dynamicFieldKey: "employeeName",
    },
    // Designation
    {
      id: "f-emp-role",
      name: "Designation / Title",
      type: "text",
      targetSide: "front",
      x: 38,
      y: 30,
      width: 55,
      height: 4.5,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "Senior Solutions Architect",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 7.5,
      fontWeight: "600",
      textAlign: "left",
      textColor: "#0284c7",
      dynamicFieldKey: "designation",
    },
    // Details Grid: Dept & ID
    {
      id: "f-emp-id-label",
      name: "ID Label",
      type: "text",
      targetSide: "front",
      x: 38,
      y: 35.5,
      width: 25,
      height: 3,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "EMPLOYEE ID",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 5.5,
      fontWeight: "700",
      textAlign: "left",
      textColor: "#64748b",
    },
    {
      id: "f-emp-id-val",
      name: "ID Value",
      type: "text",
      targetSide: "front",
      x: 38,
      y: 38.5,
      width: 25,
      height: 4,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "EMP-84920-T",
      fontFamily: "JetBrains Mono",
      fontSize: 7,
      fontWeight: "700",
      textAlign: "left",
      textColor: "#0f172a",
      dynamicFieldKey: "employeeId",
    },
    {
      id: "f-emp-dept-label",
      name: "Dept Label",
      type: "text",
      targetSide: "front",
      x: 65,
      y: 35.5,
      width: 28,
      height: 3,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "DEPARTMENT",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 5.5,
      fontWeight: "700",
      textAlign: "left",
      textColor: "#64748b",
    },
    {
      id: "f-emp-dept-val",
      name: "Dept Value",
      type: "text",
      targetSide: "front",
      x: 65,
      y: 38.5,
      width: 28,
      height: 4,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "Cloud Systems",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 7,
      fontWeight: "700",
      textAlign: "left",
      textColor: "#0f172a",
      dynamicFieldKey: "department",
    },
    // Issued & Expiry
    {
      id: "f-emp-issue-label",
      name: "Issued Label",
      type: "text",
      targetSide: "front",
      x: 38,
      y: 43.5,
      width: 25,
      height: 3,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "ISSUED",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 5.5,
      fontWeight: "700",
      textAlign: "left",
      textColor: "#64748b",
    },
    {
      id: "f-emp-issue-val",
      name: "Issued Value",
      type: "text",
      targetSide: "front",
      x: 38,
      y: 46.5,
      width: 25,
      height: 4,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "01/2025",
      fontFamily: "JetBrains Mono",
      fontSize: 6.5,
      fontWeight: "700",
      textAlign: "left",
      textColor: "#0f172a",
    },
    {
      id: "f-emp-expiry-label",
      name: "Expiry Label",
      type: "text",
      targetSide: "front",
      x: 65,
      y: 43.5,
      width: 28,
      height: 3,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "EXPIRES",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 5.5,
      fontWeight: "700",
      textAlign: "left",
      textColor: "#64748b",
    },
    {
      id: "f-emp-expiry-val",
      name: "Expiry Value",
      type: "text",
      targetSide: "front",
      x: 65,
      y: 46.5,
      width: 28,
      height: 4,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "12/2028",
      fontFamily: "JetBrains Mono",
      fontSize: 6.5,
      fontWeight: "700",
      textAlign: "left",
      textColor: "#0f172a",
      dynamicFieldKey: "validThru",
    },
    // Bottom Security Strip
    {
      id: "f-bottom-strip",
      name: "Bottom Security Strip",
      type: "shape",
      targetSide: "front",
      x: 9.7,
      y: 53.5,
      width: 85.6,
      height: 10.5,
      rotation: 0,
      opacity: 1,
      zIndex: 1,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      shapeType: "rect",
      fillColor: "#0f172a",
      strokeWidth: 0,
    },
    {
      id: "f-bottom-text",
      name: "Security Text",
      type: "text",
      targetSide: "front",
      x: 12,
      y: 57,
      width: 81,
      height: 4,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "SECURE ACCESS • ISO/IEC 7810 ID-1 • NON-TRANSFERABLE",
      fontFamily: "JetBrains Mono",
      fontSize: 5.5,
      fontWeight: "700",
      textAlign: "center",
      textColor: "#38bdf8",
      letterSpacing: 0.5,
    },
  ];

  // Back Objects (Standard CR-80 85.6 × 54.0 mm centered in 105 × 74 mm zone)
  const backObjects: CardObject[] = [
    // Top Bar
    {
      id: "b-header-bar",
      name: "Back Top Bar",
      type: "shape",
      targetSide: "back",
      x: 9.7,
      y: 10,
      width: 85.6,
      height: 7,
      rotation: 0,
      opacity: 1,
      zIndex: 1,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      shapeType: "rect",
      fillColor: "#0f172a",
    },
    {
      id: "b-header-title",
      name: "Security Instructions",
      type: "text",
      targetSide: "back",
      x: 12,
      y: 11.5,
      width: 81,
      height: 4,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "SECURITY NOTICE & TERMS OF ACCESS",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 6,
      fontWeight: "700",
      textAlign: "center",
      textColor: "#38bdf8",
    },
    // Terms text block
    {
      id: "b-terms-text",
      name: "Terms Text",
      type: "text",
      targetSide: "back",
      x: 13,
      y: 18.5,
      width: 79,
      height: 10,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "This card remains the property of Titan Global Industries. It must be surrendered upon termination of employment or request by security. Loss or theft must be reported immediately to Corporate Security.",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 5,
      lineHeight: 1.3,
      fontWeight: "normal",
      textAlign: "left",
      textColor: "#475569",
    },
    // Barcode at bottom-left
    {
      id: "b-barcode",
      name: "Card Barcode",
      type: "barcode",
      targetSide: "back",
      x: 13,
      y: 29.5,
      width: 46,
      height: 10,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      barcodeType: "code128",
      barcodeValue: "EMP-84920-TITAN",
      displayBarcodeText: true,
      src: barcodeData,
    },
    // QR Code for verification
    {
      id: "b-qrcode",
      name: "Digital Verification QR",
      type: "qrcode",
      targetSide: "back",
      x: 63,
      y: 29.5,
      width: 13,
      height: 13,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: true,
      flipX: false,
      flipY: false,
      qrValue: "https://verify.titan-industries.com/id/EMP-84920-TITAN",
      qrForegroundColor: "#0f172a",
      qrBackgroundColor: "#ffffff",
    },
    // Signature Line
    {
      id: "b-sig-line",
      name: "Signature Line",
      type: "shape",
      targetSide: "back",
      x: 78,
      y: 38,
      width: 16,
      height: 0.3,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      shapeType: "line",
      strokeColor: "#94a3b8",
      strokeWidth: 0.4,
    },
    {
      id: "b-sig-label",
      name: "Signature Label",
      type: "text",
      targetSide: "back",
      x: 78,
      y: 39,
      width: 16,
      height: 3,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "SIGNATURE",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 4.5,
      fontWeight: "700",
      textAlign: "center",
      textColor: "#64748b",
    },
    // Contact Info Box
    {
      id: "b-contact-box",
      name: "Contact Box",
      type: "shape",
      targetSide: "back",
      x: 13,
      y: 42,
      width: 79,
      height: 14,
      rotation: 0,
      opacity: 1,
      zIndex: 1,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      shapeType: "rounded-rect",
      cornerRadius: 1.5,
      fillColor: "#f8fafc",
      strokeColor: "#e2e8f0",
      strokeWidth: 0.4,
    },
    {
      id: "b-contact-title",
      name: "Emergency Header",
      type: "text",
      targetSide: "back",
      x: 15,
      y: 43.5,
      width: 75,
      height: 3,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "IF FOUND, RETURN TO CORPORATE SECURITY:",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 5,
      fontWeight: "700",
      textColor: "#0f172a",
    },
    {
      id: "b-contact-addr",
      name: "Company Address",
      type: "text",
      targetSide: "back",
      x: 15,
      y: 47,
      width: 75,
      height: 8,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "Security Operations Division • 100 Innovation Boulevard • Hotline: +1 (800) 555-0199\nEmail: security@titan-industries.com • Valid worldwide",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 4.8,
      lineHeight: 1.3,
      textColor: "#334155",
    },
    // Bottom Disclaimer Strip
    {
      id: "b-bottom-strip",
      name: "Bottom Disclaimer Strip",
      type: "shape",
      targetSide: "back",
      x: 9.7,
      y: 58,
      width: 85.6,
      height: 6,
      rotation: 0,
      opacity: 1,
      zIndex: 1,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      shapeType: "rect",
      fillColor: "#1e293b",
    },
    {
      id: "b-expiry-text",
      name: "Expiry Date",
      type: "text",
      targetSide: "back",
      x: 12,
      y: 59.5,
      width: 81,
      height: 3.5,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "VALID THRU: 12/2028  •  BLOOD GROUP: O+  •  PROPERTY OF TITAN GLOBAL",
      fontFamily: "JetBrains Mono",
      fontSize: 5.5,
      fontWeight: "700",
      textAlign: "center",
      textColor: "#f8fafc",
      dynamicFieldKey: "validThru",
    },
  ];

  project.front.objects = frontObjects;
  project.back.objects = backObjects;

  return project;
}

export function createOfficialSecurityServiceTemplate(): CardDesignerProject {
  const project = createBlankProject("Official Service Card", "portrait");
  const barcodeData = generateBarcodeDataUrl("SVC-990214-DEPT", "code128", { height: 40 });

  // Front Objects (Standard CR-80 85.6 × 54.0 mm centered in 105 × 74 mm zone: x: 9.7 to 95.3, y: 10.0 to 64.0)
  const frontObjects: CardObject[] = [
    // Official Gold/Amber Trim
    {
      id: "sec-f-border",
      name: "Security Border",
      type: "shape",
      targetSide: "front",
      x: 11,
      y: 11.5,
      width: 83,
      height: 51,
      rotation: 0,
      opacity: 1,
      zIndex: 1,
      visible: true,
      locked: true,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      shapeType: "rounded-rect",
      cornerRadius: 2.5,
      fillColor: "transparent",
      strokeColor: "#d97706", // Amber 600
      strokeWidth: 0.7,
    },
    {
      id: "sec-f-top-badge",
      name: "Security Seal Badge",
      type: "shape",
      targetSide: "front",
      x: 14,
      y: 13,
      width: 8,
      height: 8,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: true,
      flipX: false,
      flipY: false,
      shapeType: "star",
      fillColor: "#d97706",
    },
    {
      id: "sec-f-authority",
      name: "Department Authority",
      type: "text",
      targetSide: "front",
      x: 23,
      y: 13,
      width: 68,
      height: 5,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "DEPARTMENT OF PUBLIC SAFETY",
      fontFamily: "Cinzel",
      fontSize: 8.5,
      fontWeight: "800",
      textAlign: "left",
      letterSpacing: 0.8,
      textColor: "#78350f",
    },
    {
      id: "sec-f-pass-title",
      name: "Pass Designation",
      type: "text",
      targetSide: "front",
      x: 23,
      y: 17.5,
      width: 68,
      height: 4,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "OFFICIAL CREDENTIAL PASS",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 6.5,
      fontWeight: "700",
      textAlign: "left",
      letterSpacing: 1.2,
      textColor: "#b45309",
    },
    // Photo Frame
    {
      id: "sec-f-photo",
      name: "Officer Photo Frame",
      type: "shape",
      targetSide: "front",
      x: 14,
      y: 23.5,
      width: 22,
      height: 27,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: true,
      flipX: false,
      flipY: false,
      shapeType: "rounded-rect",
      cornerRadius: 2,
      fillColor: "#fef3c7",
      strokeColor: "#d97706",
      strokeWidth: 0.6,
    },
    {
      id: "sec-f-photo-txt",
      name: "Photo Placeholder",
      type: "text",
      targetSide: "front",
      x: 14,
      y: 35,
      width: 22,
      height: 5,
      rotation: 0,
      opacity: 0.8,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "OFFICER\nPHOTO",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 5.5,
      fontWeight: "700",
      textAlign: "center",
      textColor: "#92400e",
    },
    // Officer Name & Rank
    {
      id: "sec-f-name",
      name: "Officer Name",
      type: "text",
      targetSide: "front",
      x: 39,
      y: 23.5,
      width: 53,
      height: 5.5,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "CAPT. MARCUS V. HOLLOWAY",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 9.5,
      fontWeight: "800",
      textAlign: "left",
      textColor: "#1e293b",
    },
    {
      id: "sec-f-rank",
      name: "Rank & Unit",
      type: "text",
      targetSide: "front",
      x: 39,
      y: 29.5,
      width: 53,
      height: 4,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "Special Operations Command • Division 04",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 6.5,
      fontWeight: "600",
      textAlign: "left",
      textColor: "#b45309",
    },
    {
      id: "sec-f-clearance",
      name: "Clearance Level",
      type: "text",
      targetSide: "front",
      x: 39,
      y: 35,
      width: 32,
      height: 4.5,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "CLEARANCE: LEVEL 5 (ALPHA)",
      fontFamily: "JetBrains Mono",
      fontSize: 6,
      fontWeight: "800",
      textAlign: "left",
      textColor: "#b91c1c",
    },
    {
      id: "sec-f-badge-num",
      name: "Badge Number",
      type: "text",
      targetSide: "front",
      x: 39,
      y: 40,
      width: 32,
      height: 4,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "BADGE: #7402-DPS",
      fontFamily: "JetBrains Mono",
      fontSize: 6,
      fontWeight: "700",
      textAlign: "left",
      textColor: "#1e293b",
    },
    // QR authentication square
    {
      id: "sec-f-qr",
      name: "Encrypted QR Token",
      type: "qrcode",
      targetSide: "front",
      x: 74,
      y: 35,
      width: 17,
      height: 17,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: true,
      flipX: false,
      flipY: false,
      qrValue: "DPS-AUTH-TOKEN-7402-SECRET",
      qrForegroundColor: "#78350f",
      qrBackgroundColor: "#ffffff",
    },
    // Bottom Warning Banner
    {
      id: "sec-f-banner",
      name: "Bottom Warning",
      type: "shape",
      targetSide: "front",
      x: 11,
      y: 54,
      width: 83,
      height: 8.5,
      rotation: 0,
      opacity: 1,
      zIndex: 1,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      shapeType: "rect",
      fillColor: "#78350f",
      strokeWidth: 0,
    },
    {
      id: "sec-f-banner-text",
      name: "Security Text",
      type: "text",
      targetSide: "front",
      x: 12,
      y: 56.5,
      width: 81,
      height: 3.5,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "OFFICIAL GOVERNMENT CREDENTIAL • UNAUTHORIZED USE IS A FEDERAL OFFENSE",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 4.8,
      fontWeight: "700",
      textAlign: "center",
      textColor: "#fef3c7",
    },
  ];

  // Back Objects
  const backObjects: CardObject[] = [
    // Mag stripe
    {
      id: "sec-b-magstripe",
      name: "Magnetic Stripe Simulation",
      type: "shape",
      targetSide: "back",
      x: 9.7,
      y: 12,
      width: 85.6,
      height: 11,
      rotation: 0,
      opacity: 1,
      zIndex: 1,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      shapeType: "rect",
      fillColor: "#1e1e24",
    },
    // Barcode
    {
      id: "sec-b-barcode",
      name: "Service Barcode",
      type: "barcode",
      targetSide: "back",
      x: 13,
      y: 26,
      width: 50,
      height: 10,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      barcodeType: "code128",
      barcodeValue: "SVC-990214-DEPT",
      displayBarcodeText: true,
      src: barcodeData,
    },
    // Official Seal text
    {
      id: "sec-b-seal",
      name: "Department Seal Box",
      type: "shape",
      targetSide: "back",
      x: 67,
      y: 26,
      width: 25,
      height: 16,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      shapeType: "rounded-rect",
      cornerRadius: 1.5,
      fillColor: "#fef3c7",
      strokeColor: "#d97706",
      strokeWidth: 0.5,
    },
    {
      id: "sec-b-seal-txt",
      name: "Seal Text",
      type: "text",
      targetSide: "back",
      x: 68,
      y: 29,
      width: 23,
      height: 10,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "OFFICIAL SEAL\nPUBLIC SAFETY\nVERIFIED",
      fontFamily: "Cinzel",
      fontSize: 5,
      fontWeight: "800",
      textAlign: "center",
      textColor: "#78350f",
    },
    // Legal instructions
    {
      id: "sec-b-legal",
      name: "Legal Instructions",
      type: "text",
      targetSide: "back",
      x: 13,
      y: 39,
      width: 52,
      height: 13,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "This document certifies that the bearer is an authorized agent of the Department of Public Safety. Possession by any other person constitutes a violation of statutory law. If found, surrender to the nearest federal or state law enforcement facility.",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 4.8,
      lineHeight: 1.3,
      textColor: "#475569",
    },
    // Emergency Hotline
    {
      id: "sec-b-hotline",
      name: "Emergency Hotline",
      type: "text",
      targetSide: "back",
      x: 13,
      y: 55,
      width: 79,
      height: 4,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "24/7 COMMAND DISPATCH HOTLINE: +1 (800) 555-9110 • EXPIRES: 12/2029",
      fontFamily: "JetBrains Mono",
      fontSize: 5.5,
      fontWeight: "700",
      textAlign: "center",
      textColor: "#78350f",
    },
  ];

  project.front.objects = frontObjects;
  project.back.objects = backObjects;
  return project;
}

export const createDefaultProject = () => createBlankProject("Custom Card Design", "portrait");
export const createOfficialServiceTemplate = createOfficialSecurityServiceTemplate;

export function createVisitorAccessTemplate(): CardDesignerProject {
  const project = createBlankProject("Visitor Access Badge", "portrait");

  // Front Objects (Standard CR-80 85.6 × 54.0 mm centered in 105 × 74 mm zone: x: 9.7 to 95.3, y: 10.0 to 64.0)
  const frontObjects: CardObject[] = [
    {
      id: "vis-f-header",
      name: "Visitor Banner",
      type: "shape",
      targetSide: "front",
      x: 9.7,
      y: 10,
      width: 85.6,
      height: 14,
      rotation: 0,
      opacity: 1,
      zIndex: 1,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      shapeType: "rect",
      fillColor: "#ea580c", // Orange
      strokeWidth: 0,
    },
    {
      id: "vis-f-title",
      name: "Visitor Text",
      type: "text",
      targetSide: "front",
      x: 12,
      y: 12.5,
      width: 81,
      height: 8,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "GUEST VISITOR PASS",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 13,
      fontWeight: "900",
      textAlign: "center",
      textColor: "#ffffff",
      letterSpacing: 1.5,
    },
    {
      id: "vis-f-date-badge",
      name: "Date Badge",
      type: "shape",
      targetSide: "front",
      x: 13,
      y: 27,
      width: 32,
      height: 12,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      shapeType: "rounded-rect",
      cornerRadius: 2,
      fillColor: "#ffedd5",
      strokeColor: "#f97316",
      strokeWidth: 0.6,
    },
    {
      id: "vis-f-date-text",
      name: "Date Text",
      type: "text",
      targetSide: "front",
      x: 13,
      y: 30,
      width: 32,
      height: 6,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "VALID TODAY ONLY",
      fontFamily: "JetBrains Mono",
      fontSize: 7,
      fontWeight: "800",
      textAlign: "center",
      textColor: "#9a3412",
    },
    {
      id: "vis-f-name",
      name: "Visitor Name",
      type: "text",
      targetSide: "front",
      x: 48,
      y: 27,
      width: 44,
      height: 6,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "TEMPORARY GUEST",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 10,
      fontWeight: "800",
      textAlign: "left",
      textColor: "#1e293b",
      dynamicFieldKey: "employeeName",
    },
    {
      id: "vis-f-host",
      name: "Host Label",
      type: "text",
      targetSide: "front",
      x: 48,
      y: 33,
      width: 44,
      height: 5,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "Host: Operations Command Center",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 6.5,
      fontWeight: "500",
      textAlign: "left",
      textColor: "#64748b",
    },
    // QR Code for visitor gate access
    {
      id: "vis-f-qr",
      name: "Access QR",
      type: "qrcode",
      targetSide: "front",
      x: 73,
      y: 42,
      width: 17,
      height: 17,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: true,
      flipX: false,
      flipY: false,
      qrValue: "VISITOR-AUTH-TEMP-SESSION",
    },
    {
      id: "vis-f-escort",
      name: "Escort Notice",
      type: "text",
      targetSide: "front",
      x: 13,
      y: 43,
      width: 58,
      height: 8,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "ESCORT REQUIRED AT ALL TIMES IN SENSITIVE ZONES\nBADGE MUST BE RETURNED UPON EXIT",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 5.5,
      fontWeight: "700",
      textAlign: "left",
      textColor: "#b45309",
    },
    // Bottom Bar
    {
      id: "vis-f-bottom",
      name: "Visitor Bottom Bar",
      type: "shape",
      targetSide: "front",
      x: 9.7,
      y: 60,
      width: 85.6,
      height: 4,
      rotation: 0,
      opacity: 1,
      zIndex: 1,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      shapeType: "rect",
      fillColor: "#ea580c",
      strokeWidth: 0,
    },
  ];

  const backObjects: CardObject[] = [
    {
      id: "vis-b-rules-title",
      name: "Rules Heading",
      type: "text",
      targetSide: "back",
      x: 13,
      y: 14,
      width: 79,
      height: 6,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "FACILITY VISITOR PROTOCOL & RULES",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 8,
      fontWeight: "800",
      textAlign: "center",
      textColor: "#0f172a",
    },
    {
      id: "vis-b-rules-body",
      name: "Rules Text",
      type: "text",
      targetSide: "back",
      x: 13,
      y: 22,
      width: 79,
      height: 28,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "1. Badge must be visibly worn above the waist at all times.\n2. Visitors must remain accompanied by their designated host at all times.\n3. Photography and recording are strictly prohibited inside the facility.\n4. Return this badge to the reception desk or turnstile slot upon departure.\n5. In case of emergency, follow instructions of safety wardens immediately.",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 5.5,
      lineHeight: 1.4,
      textColor: "#334155",
    },
    {
      id: "vis-b-emergency",
      name: "Emergency Hotline",
      type: "text",
      targetSide: "back",
      x: 13,
      y: 53,
      width: 79,
      height: 5,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "FACILITY COMMAND & SAFETY DESK: EXT. 4000 • DIAL 911 FOR EMERGENCIES",
      fontFamily: "JetBrains Mono",
      fontSize: 5.5,
      fontWeight: "700",
      textAlign: "center",
      textColor: "#ea580c",
    },
  ];

  project.front.objects = frontObjects;
  project.back.objects = backObjects;
  return project;
}

export const BUILTIN_TEMPLATES = [
  { id: "corporate-employee", name: "Corporate Employee Badge", description: "Standard CR-80 photo ID with barcode, QR code, company branding, and policy backing.", creator: createCorporateEmployeeTemplate },
  { id: "official-service", name: "Official Service & Security Pass", description: "High-security card with gold border, emblem, clearance level, and magnetic stripe simulation.", creator: createOfficialSecurityServiceTemplate },
  { id: "visitor-access", name: "Visitor Access Badge", description: "Bright guest visitor pass with safety protocol backing and temporary QR code.", creator: createVisitorAccessTemplate },
  { id: "blank-dual-a6", name: "Blank A6 Dual-Card Canvas", description: "Empty canvas with Front at top (105×74mm) and Back underneath (105×74mm) on one physical A6 sheet.", creator: () => createBlankProject("Custom Card Design", "portrait") },
];
