/**
 * Built-in Professional Starter Templates for ID & Service Card Designer
 * Pre-configured dual-card layouts on a single A6 page (Front on top, Back underneath).
 */

import { CardDesignerProject, CardObject } from "./types";
import { generateBarcodeDataUrl } from "./barcodeGenerator";

export function createBlankProject(
  name: string = "Untitled Card Design",
  orientation: "portrait" | "landscape" = "portrait"
): CardDesignerProject {
  const isPortrait = orientation === "portrait";
  // A6 sheet: 105 x 148 mm in portrait, 148 x 105 mm in landscape
  const pageWidthMm = isPortrait ? 105 : 148;
  const pageHeightMm = isPortrait ? 148 : 105;

  // In portrait A6: sheet is 105mm wide x 148mm high.
  // Upper half zone (front): 105mm wide x 74mm high at (0, 0)
  // Lower half zone (back): 105mm wide x 74mm high at (0, 74)
  const cardWidthMm = 105;
  const cardHeightMm = 74;

  const frontPosMm = isPortrait
    ? { x: 0, y: 0 }
    : { x: 5, y: Math.max(0, (pageHeightMm - cardHeightMm) / 2) };

  const backPosMm = isPortrait
    ? { x: 0, y: 74 }
    : { x: 5 + cardWidthMm + 8, y: Math.max(0, (pageHeightMm - cardHeightMm) / 2) };

  return {
    id: `card-proj-${Date.now()}`,
    name,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    pageFormat: "A6",
    orientation,
    pageWidthMm,
    pageHeightMm,
    cardWidthMm,
    cardHeightMm,
    trueCardWidthMm: 85.6,
    trueCardHeightMm: 54.0,
    trueCardOrientation: "landscape",
    cardPreset: "id1_cr80",
    showCardBoundary: true,
    showBleedShading: true,
    cardCornerRadiusMm: 3.18,
    frontPosMm,
    backPosMm,
    safeAreaMarginMm: 3,
    bleedMarginMm: 2,
    cuttingGuides: true,
    showBleed: false,
    showSafeArea: true,
    showRulers: true,
    showGrid: false,
    snapToGrid: true,
    snapToObjects: true,
    snapToCardBoundary: true,
    gridSizeMm: 2,
    guides: {
      horizontal: [10, 64, 84, 138],
      vertical: [9.7, 95.3],
    },
    front: {
      background: {
        type: "solid",
        color1: "#ffffff",
      },
      objects: [],
    },
    back: {
      background: {
        type: "solid",
        color1: "#ffffff",
      },
      objects: [],
    },
  };
}

export function createCorporateEmployeeTemplate(): CardDesignerProject {
  const project = createBlankProject("Corporate Employee Badge", "portrait");
  const barcodeData = generateBarcodeDataUrl("EMP-84920-TITAN", "code128", { height: 40 });

  // Front Objects (74 × 105 mm)
  const frontObjects: CardObject[] = [
    // Header Banner
    {
      id: "f-banner-bg",
      name: "Header Banner",
      type: "shape",
      targetSide: "front",
      x: 0,
      y: 0,
      width: 74,
      height: 22,
      rotation: 0,
      opacity: 1,
      zIndex: 1,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      shapeType: "rect",
      fillColor: "#0f172a", // Deep Navy
      strokeWidth: 0,
    },
    {
      id: "f-company-name",
      name: "Company Name",
      type: "text",
      targetSide: "front",
      x: 3,
      y: 4,
      width: 68,
      height: 6,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "TITAN GLOBAL INDUSTRIES",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 10,
      fontWeight: "700",
      textAlign: "center",
      letterSpacing: 1,
      textColor: "#38bdf8", // Sky blue
      dynamicFieldKey: "companyName",
    },
    {
      id: "f-company-subtitle",
      name: "Company Subtitle",
      type: "text",
      targetSide: "front",
      x: 3,
      y: 11,
      width: 68,
      height: 5,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "AUTHORISED IDENTITY & ACCESS PASS",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 6,
      fontWeight: "600",
      textAlign: "center",
      letterSpacing: 0.5,
      textColor: "#94a3b8",
    },
    // Accent Stripe
    {
      id: "f-accent-stripe",
      name: "Accent Stripe",
      type: "shape",
      targetSide: "front",
      x: 0,
      y: 21,
      width: 74,
      height: 1.5,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      shapeType: "rect",
      fillColor: "#0ea5e9", // Sky 500
    },
    // Photo Frame / Placeholder Box
    {
      id: "f-photo-frame",
      name: "Photo Placeholder Frame",
      type: "shape",
      targetSide: "front",
      x: 23,
      y: 26,
      width: 28,
      height: 34,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: true,
      flipX: false,
      flipY: false,
      shapeType: "rounded-rect",
      cornerRadius: 2,
      fillColor: "#f1f5f9",
      strokeColor: "#cbd5e1",
      strokeWidth: 0.5,
    },
    {
      id: "f-photo-hint",
      name: "Photo Label",
      type: "text",
      targetSide: "front",
      x: 23,
      y: 40,
      width: 28,
      height: 6,
      rotation: 0,
      opacity: 0.7,
      zIndex: 4,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "PHOTO",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 8,
      fontWeight: "700",
      textAlign: "center",
      textColor: "#64748b",
    },
    // Employee Name
    {
      id: "f-emp-name",
      name: "Employee Full Name",
      type: "text",
      targetSide: "front",
      x: 4,
      y: 63,
      width: 66,
      height: 7,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "ALEXANDER M. HAYES",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 12,
      fontWeight: "800",
      textAlign: "center",
      textColor: "#0f172a",
      dynamicFieldKey: "employeeName",
    },
    // Designation
    {
      id: "f-emp-role",
      name: "Designation / Title",
      type: "text",
      targetSide: "front",
      x: 4,
      y: 70,
      width: 66,
      height: 5,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "Senior Solutions Architect",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 8,
      fontWeight: "600",
      textAlign: "center",
      textColor: "#0284c7",
      dynamicFieldKey: "designation",
    },
    // Details Grid: Dept & ID
    {
      id: "f-emp-id-label",
      name: "ID Label",
      type: "text",
      targetSide: "front",
      x: 6,
      y: 77,
      width: 30,
      height: 4,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "EMPLOYEE ID",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 6,
      fontWeight: "700",
      textAlign: "left",
      textColor: "#64748b",
    },
    {
      id: "f-emp-id-val",
      name: "ID Value",
      type: "text",
      targetSide: "front",
      x: 6,
      y: 81,
      width: 30,
      height: 5,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "EMP-84920-T",
      fontFamily: "JetBrains Mono",
      fontSize: 7.5,
      fontWeight: "700",
      textAlign: "left",
      textColor: "#0f172a",
      dynamicFieldKey: "employeeId",
    },
    {
      id: "f-emp-dept-label",
      name: "Dept Label",
      type: "text",
      targetSide: "front",
      x: 38,
      y: 77,
      width: 30,
      height: 4,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "DEPARTMENT",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 6,
      fontWeight: "700",
      textAlign: "right",
      textColor: "#64748b",
    },
    {
      id: "f-emp-dept-val",
      name: "Dept Value",
      type: "text",
      targetSide: "front",
      x: 38,
      y: 81,
      width: 30,
      height: 5,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "Cloud Engineering",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 7.5,
      fontWeight: "700",
      textAlign: "right",
      textColor: "#0f172a",
      dynamicFieldKey: "department",
    },
    // Barcode Object at bottom
    {
      id: "f-barcode",
      name: "Card Barcode",
      type: "barcode",
      targetSide: "front",
      x: 10,
      y: 88,
      width: 54,
      height: 12,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      barcodeType: "code128",
      barcodeValue: "EMP-84920-TITAN",
      displayBarcodeText: true,
      src: barcodeData,
    },
  ];

  // Back Objects (74 × 105 mm)
  const backObjects: CardObject[] = [
    // Top Bar
    {
      id: "b-header-bar",
      name: "Back Top Bar",
      type: "shape",
      targetSide: "back",
      x: 0,
      y: 0,
      width: 74,
      height: 8,
      rotation: 0,
      opacity: 1,
      zIndex: 1,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      shapeType: "rect",
      fillColor: "#0f172a",
    },
    {
      id: "b-header-title",
      name: "Security Instructions",
      type: "text",
      targetSide: "back",
      x: 4,
      y: 2,
      width: 66,
      height: 4,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "SECURITY NOTICE & TERMS OF ACCESS",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 6.5,
      fontWeight: "700",
      textAlign: "center",
      textColor: "#f8fafc",
    },
    // Terms text block
    {
      id: "b-terms-text",
      name: "Terms Text",
      type: "text",
      targetSide: "back",
      x: 6,
      y: 12,
      width: 62,
      height: 25,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "This card remains the property of Titan Global Industries. It must be surrendered upon termination of employment or upon request by security. Loss or theft must be reported immediately to Corporate Security.",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 6,
      lineHeight: 1.35,
      fontWeight: "normal",
      textAlign: "left",
      textColor: "#475569",
    },
    // Contact Info Box
    {
      id: "b-contact-box",
      name: "Contact Box",
      type: "shape",
      targetSide: "back",
      x: 6,
      y: 38,
      width: 62,
      height: 22,
      rotation: 0,
      opacity: 1,
      zIndex: 1,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      shapeType: "rounded-rect",
      cornerRadius: 1.5,
      fillColor: "#f8fafc",
      strokeColor: "#e2e8f0",
      strokeWidth: 0.4,
    },
    {
      id: "b-contact-title",
      name: "Emergency Header",
      type: "text",
      targetSide: "back",
      x: 8,
      y: 40,
      width: 58,
      height: 3.5,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "IF FOUND, PLEASE RETURN TO:",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 5.5,
      fontWeight: "700",
      textColor: "#0f172a",
    },
    {
      id: "b-contact-addr",
      name: "Company Address",
      type: "text",
      targetSide: "back",
      x: 8,
      y: 44,
      width: 58,
      height: 14,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "Security Operations Division\n100 Innovation Boulevard, Tech Park\nHotline: +1 (800) 555-0199\nEmail: security@titan-industries.com",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 5.5,
      lineHeight: 1.3,
      textColor: "#334155",
    },
    // Signature Area
    {
      id: "b-sig-line",
      name: "Signature Line",
      type: "shape",
      targetSide: "back",
      x: 6,
      y: 75,
      width: 38,
      height: 0.3,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      shapeType: "line",
      strokeColor: "#94a3b8",
      strokeWidth: 0.4,
    },
    {
      id: "b-sig-label",
      name: "Signature Label",
      type: "text",
      targetSide: "back",
      x: 6,
      y: 76.5,
      width: 38,
      height: 4,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "AUTHORIZED SIGNATURE",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 5.5,
      fontWeight: "700",
      textColor: "#64748b",
    },
    // QR Code for verification
    {
      id: "b-qrcode",
      name: "Digital Verification QR",
      type: "qrcode",
      targetSide: "back",
      x: 48,
      y: 63,
      width: 20,
      height: 20,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: true,
      flipX: false,
      flipY: false,
      qrValue: "https://verify.titan-industries.com/id/EMP-84920-TITAN",
      qrForegroundColor: "#0f172a",
      qrBackgroundColor: "#ffffff",
    },
    // Expiry Notice
    {
      id: "b-expiry-text",
      name: "Expiry Date",
      type: "text",
      targetSide: "back",
      x: 6,
      y: 86,
      width: 62,
      height: 5,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "VALID THRU: 12/2028  •  BLOOD GROUP: O+",
      fontFamily: "JetBrains Mono",
      fontSize: 6.5,
      fontWeight: "700",
      textAlign: "center",
      textColor: "#0f172a",
      dynamicFieldKey: "validThru",
    },
  ];

  project.front.objects = frontObjects;
  project.back.objects = backObjects;

  return project;
}

export function createOfficialSecurityServiceTemplate(): CardDesignerProject {
  const project = createBlankProject("Official Service Card", "portrait");
  const barcodeData = generateBarcodeDataUrl("SVC-990214-DEPT", "code128", { height: 40 });

  // Front Objects (74 × 105 mm)
  const frontObjects: CardObject[] = [
    // Official Gold/Amber Trim
    {
      id: "sec-f-border",
      name: "Security Border",
      type: "shape",
      targetSide: "front",
      x: 1.5,
      y: 1.5,
      width: 71,
      height: 102,
      rotation: 0,
      opacity: 1,
      zIndex: 1,
      visible: true,
      locked: true,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      shapeType: "rounded-rect",
      cornerRadius: 3,
      fillColor: "transparent",
      strokeColor: "#d97706", // Amber 600
      strokeWidth: 0.8,
    },
    {
      id: "sec-f-top-badge",
      name: "Security Seal Badge",
      type: "shape",
      targetSide: "front",
      x: 32,
      y: 4,
      width: 10,
      height: 10,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: true,
      flipX: false,
      flipY: false,
      shapeType: "star",
      fillColor: "#d97706",
    },
    {
      id: "sec-f-authority",
      name: "Department Authority",
      type: "text",
      targetSide: "front",
      x: 4,
      y: 16,
      width: 66,
      height: 6,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "DEPARTMENT OF PUBLIC SAFETY",
      fontFamily: "Cinzel",
      fontSize: 9,
      fontWeight: "800",
      textAlign: "center",
      letterSpacing: 0.8,
      textColor: "#78350f",
    },
    {
      id: "sec-f-pass-title",
      name: "Pass Designation",
      type: "text",
      targetSide: "front",
      x: 4,
      y: 23,
      width: 66,
      height: 5,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "OFFICIAL CREDENTIAL PASS",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 7,
      fontWeight: "700",
      textAlign: "center",
      letterSpacing: 1.2,
      textColor: "#b45309",
    },
    // Officer Name
    {
      id: "sec-f-officer-name",
      name: "Officer Name",
      type: "text",
      targetSide: "front",
      x: 4,
      y: 60,
      width: 66,
      height: 7,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "CAPT. MARCUS T. VANCE",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 11,
      fontWeight: "800",
      textAlign: "center",
      textColor: "#0f172a",
      dynamicFieldKey: "employeeName",
    },
    // Rank & Division
    {
      id: "sec-f-rank",
      name: "Rank & Division",
      type: "text",
      targetSide: "front",
      x: 4,
      y: 68,
      width: 66,
      height: 5,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "Special Operations • Tactical Division",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 7.5,
      fontWeight: "600",
      textAlign: "center",
      textColor: "#475569",
    },
    // Badge ID Badge
    {
      id: "sec-f-badge-badge",
      name: "Badge Box",
      type: "shape",
      targetSide: "front",
      x: 18,
      y: 75,
      width: 38,
      height: 8,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      shapeType: "rounded-rect",
      cornerRadius: 1.5,
      fillColor: "#fef3c7",
      strokeColor: "#f59e0b",
      strokeWidth: 0.5,
    },
    {
      id: "sec-f-badge-no",
      name: "Badge Number",
      type: "text",
      targetSide: "front",
      x: 18,
      y: 77,
      width: 38,
      height: 4,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "BADGE # 9042-ALPHA",
      fontFamily: "JetBrains Mono",
      fontSize: 7.5,
      fontWeight: "800",
      textAlign: "center",
      textColor: "#92400e",
      dynamicFieldKey: "employeeId",
    },
    // Barcode
    {
      id: "sec-f-barcode",
      name: "Service Barcode",
      type: "barcode",
      targetSide: "front",
      x: 10,
      y: 87,
      width: 54,
      height: 12,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      barcodeType: "code128",
      barcodeValue: "SVC-990214-DEPT",
      displayBarcodeText: true,
      src: barcodeData,
    },
  ];

  // Back Objects
  const backObjects: CardObject[] = [
    // Mag stripe simulation
    {
      id: "sec-b-magstripe",
      name: "Magnetic Stripe",
      type: "shape",
      targetSide: "back",
      x: 0,
      y: 8,
      width: 74,
      height: 12,
      rotation: 0,
      opacity: 1,
      zIndex: 1,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      shapeType: "rect",
      fillColor: "#1e293b",
    },
    // Legal & Security clause
    {
      id: "sec-b-clause",
      name: "Legal Notice",
      type: "text",
      targetSide: "back",
      x: 6,
      y: 26,
      width: 62,
      height: 30,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "This credential certifies that the bearer is a commissioned officer authorized to perform official duties. Any alteration or unauthorized possession is a criminal offense under federal code. Return immediately if found to the Provost Marshal.",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 5.5,
      lineHeight: 1.4,
      textColor: "#334155",
    },
    {
      id: "sec-b-qr",
      name: "Cryptographic QR",
      type: "qrcode",
      targetSide: "back",
      x: 27,
      y: 60,
      width: 20,
      height: 20,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: true,
      flipX: false,
      flipY: false,
      qrValue: "SEC-OFFICIAL-VALIDATION-KEY-990214",
    },
    {
      id: "sec-b-seal-text",
      name: "Official Seal Text",
      type: "text",
      targetSide: "back",
      x: 6,
      y: 85,
      width: 62,
      height: 6,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "ISSUED UNDER OFFICIAL AUTHORITY • EXPIRES 2029",
      fontFamily: "JetBrains Mono",
      fontSize: 6,
      fontWeight: "700",
      textAlign: "center",
      textColor: "#78350f",
    },
  ];

  project.front.objects = frontObjects;
  project.back.objects = backObjects;
  return project;
}

export const createDefaultProject = () => createBlankProject("Custom Card Design", "portrait");
export const createOfficialServiceTemplate = createOfficialSecurityServiceTemplate;

export function createVisitorAccessTemplate(): CardDesignerProject {
  const project = createBlankProject("Visitor Access Badge", "portrait");
  const frontObjects: CardObject[] = [
    {
      id: "vis-f-bg",
      name: "Card Background",
      type: "shape",
      targetSide: "front",
      x: 0,
      y: 0,
      width: 74,
      height: 105,
      rotation: 0,
      opacity: 1,
      zIndex: 0,
      visible: true,
      locked: true,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      shapeType: "rectangle",
      fillColor: "#ffffff",
      strokeColor: "#e2e8f0",
      strokeWidth: 0.5,
    },
    {
      id: "vis-f-header",
      name: "Visitor Banner",
      type: "shape",
      targetSide: "front",
      x: 0,
      y: 0,
      width: 74,
      height: 24,
      rotation: 0,
      opacity: 1,
      zIndex: 1,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      shapeType: "rectangle",
      fillColor: "#ea580c",
      strokeColor: "transparent",
      strokeWidth: 0,
    },
    {
      id: "vis-f-title",
      name: "Visitor Text",
      type: "text",
      targetSide: "front",
      x: 0,
      y: 6,
      width: 74,
      height: 12,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "VISITOR PASS",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 16,
      fontWeight: "900",
      textAlign: "center",
      textColor: "#ffffff",
      letterSpacing: 2,
    },
    {
      id: "vis-f-date-badge",
      name: "Date Badge",
      type: "shape",
      targetSide: "front",
      x: 12,
      y: 28,
      width: 50,
      height: 12,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      shapeType: "rounded-rect",
      cornerRadius: 3,
      fillColor: "#ffedd5",
      strokeColor: "#f97316",
      strokeWidth: 1,
    },
    {
      id: "vis-f-date-text",
      name: "Date Text",
      type: "text",
      targetSide: "front",
      x: 12,
      y: 31,
      width: 50,
      height: 6,
      rotation: 0,
      opacity: 1,
      zIndex: 3,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "VALID TODAY ONLY",
      fontFamily: "JetBrains Mono",
      fontSize: 9,
      fontWeight: "800",
      textAlign: "center",
      textColor: "#9a3412",
    },
    {
      id: "vis-f-name",
      name: "Visitor Name",
      type: "text",
      targetSide: "front",
      x: 4,
      y: 46,
      width: 66,
      height: 8,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "GUEST VISITOR",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 13,
      fontWeight: "800",
      textAlign: "center",
      textColor: "#1e293b",
      dynamicFieldKey: "employeeName",
    },
    {
      id: "vis-f-host",
      name: "Host Label",
      type: "text",
      targetSide: "front",
      x: 4,
      y: 56,
      width: 66,
      height: 6,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "Host: Operations Command Center",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 8,
      fontWeight: "500",
      textAlign: "center",
      textColor: "#64748b",
    },
    {
      id: "vis-f-qr",
      name: "Access QR",
      type: "qrcode",
      targetSide: "front",
      x: 23,
      y: 66,
      width: 28,
      height: 28,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: true,
      flipX: false,
      flipY: false,
      qrValue: "VISITOR-AUTH-TEMP-SESSION",
    },
  ];

  const backObjects: CardObject[] = [
    {
      id: "vis-b-bg",
      name: "Back Background",
      type: "shape",
      targetSide: "back",
      x: 0,
      y: 0,
      width: 74,
      height: 105,
      rotation: 0,
      opacity: 1,
      zIndex: 0,
      visible: true,
      locked: true,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      shapeType: "rectangle",
      fillColor: "#f8fafc",
      strokeColor: "#e2e8f0",
      strokeWidth: 0.5,
    },
    {
      id: "vis-b-rules-title",
      name: "Rules Heading",
      type: "text",
      targetSide: "back",
      x: 6,
      y: 12,
      width: 62,
      height: 6,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "VISITOR PROTOCOL & RULES",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 8.5,
      fontWeight: "800",
      textAlign: "center",
      textColor: "#0f172a",
    },
    {
      id: "vis-b-rules-body",
      name: "Rules Text",
      type: "text",
      targetSide: "back",
      x: 6,
      y: 22,
      width: 62,
      height: 50,
      rotation: 0,
      opacity: 1,
      zIndex: 2,
      visible: true,
      locked: false,
      aspectRatioLocked: false,
      flipX: false,
      flipY: false,
      text: "1. Badge must be visibly worn above the waist at all times.\n2. Visitors must remain accompanied by their designated host.\n3. Photography and recording are strictly prohibited inside the facility.\n4. Return this badge to the reception desk upon departure.",
      fontFamily: "Plus Jakarta Sans",
      fontSize: 6.5,
      lineHeight: 1.5,
      textColor: "#334155",
    },
  ];

  project.front.objects = frontObjects;
  project.back.objects = backObjects;
  return project;
}

export const BUILTIN_TEMPLATES = [
  { id: "corporate-employee", name: "Corporate Employee Badge", description: "Standard photo ID with barcode, QR code, company branding, and policy backing.", creator: createCorporateEmployeeTemplate },
  { id: "official-service", name: "Official Service & Security Pass", description: "High-security card with gold border, emblem, clearance level, and magnetic stripe simulation.", creator: createOfficialSecurityServiceTemplate },
  { id: "visitor-access", name: "Visitor Access Badge", description: "Bright guest visitor pass with safety protocol backing and temporary QR code.", creator: createVisitorAccessTemplate },
  { id: "blank-dual-a6", name: "Blank A6 Dual-Card Canvas", description: "Empty canvas with Front at top (74×105mm) and Back underneath (74×105mm) on one physical A6 sheet.", creator: () => createBlankProject("Custom Card Design", "portrait") },
];
