/**
 * OMNISCAN TITAN X - Centralized Master Command Catalog
 * Defines every application-wide and tool-scoped command.
 */

import { CommandDefinition } from "./types";

export const MASTER_COMMAND_DEFINITIONS: CommandDefinition[] = [
  // ==========================================
  // 1. FILE OPERATIONS
  // ==========================================
  {
    id: "file.new",
    label: "New Document / Acquire Scan",
    description: "Launch hardware scanner / camera acquisition modal",
    category: "File",
    defaultShortcut: "Ctrl+N",
    alternativeShortcuts: ["Cmd+N"],
    scope: "global",
    icon: "Scan",
    keywords: ["scan", "new", "camera", "hardware", "acquire", "twain", "wia"],
  },
  {
    id: "file.open",
    label: "Open / Import Files",
    description: "Open local PDF document or image files into the workspace",
    category: "File",
    defaultShortcut: "Ctrl+O",
    alternativeShortcuts: ["Cmd+O"],
    scope: "global",
    icon: "FolderOpen",
    keywords: ["import", "open", "upload", "load", "pdf", "image"],
  },
  {
    id: "file.save",
    label: "Save Project (.titanproj)",
    description: "Save active session, pages, metadata, and history to file",
    category: "File",
    defaultShortcut: "Ctrl+S",
    alternativeShortcuts: ["Cmd+S"],
    scope: "global",
    icon: "Save",
    keywords: ["save", "project", "session", "titanproj"],
  },
  {
    id: "file.saveAs",
    label: "Save As / Export As",
    description: "Save project under a new name or export package",
    category: "File",
    defaultShortcut: "Ctrl+Shift+S",
    alternativeShortcuts: ["Cmd+Shift+S"],
    scope: "global",
    icon: "Save",
    keywords: ["save as", "export as", "backup"],
  },
  {
    id: "file.exportPdf",
    label: "Export Validated PDF/A",
    description: "Export full document as ISO 19005-1 compliant archival PDF",
    category: "File",
    defaultShortcut: "Ctrl+E",
    alternativeShortcuts: ["Cmd+E"],
    scope: "global",
    icon: "Download",
    keywords: ["export", "pdf", "pdf/a", "download", "archival"],
  },
  {
    id: "file.exportOptions",
    label: "Export with Archival Options",
    description: "Configure compression, encryption, and DPI before exporting",
    category: "File",
    defaultShortcut: "Ctrl+Shift+E",
    alternativeShortcuts: ["Cmd+Shift+E"],
    scope: "global",
    icon: "Download",
    keywords: ["export options", "dpi", "compression", "pdf settings"],
  },
  {
    id: "file.print",
    label: "Print Document",
    description: "Send active document to physical printer or system print dialog",
    category: "File",
    defaultShortcut: "Ctrl+P",
    alternativeShortcuts: ["Cmd+P"],
    scope: "global",
    icon: "Printer",
    keywords: ["print", "hardcopy", "paper", "printer"],
  },
  {
    id: "file.close",
    label: "Close Active Document / Modal",
    description: "Close current open modal or active document",
    category: "File",
    defaultShortcut: "Ctrl+W",
    alternativeShortcuts: ["Cmd+W"],
    scope: "global",
    icon: "X",
    keywords: ["close", "exit", "quit"],
  },

  // ==========================================
  // 2. EDIT OPERATIONS
  // ==========================================
  {
    id: "edit.undo",
    label: "Undo",
    description: "Undo the previous editing, rotation, or filter action",
    category: "Edit",
    defaultShortcut: "Ctrl+Z",
    alternativeShortcuts: ["Cmd+Z"],
    scope: "global",
    icon: "Undo2",
    keywords: ["undo", "revert", "step back"],
  },
  {
    id: "edit.redo",
    label: "Redo",
    description: "Redo the previously undone action",
    category: "Edit",
    defaultShortcut: "Ctrl+Shift+Z",
    alternativeShortcuts: ["Cmd+Shift+Z", "Ctrl+Y", "Cmd+Y"],
    scope: "global",
    icon: "Redo2",
    keywords: ["redo", "repeat", "step forward"],
  },
  {
    id: "edit.copy",
    label: "Copy Selected Item / Page",
    description: "Copy selected page or annotation element to clipboard",
    category: "Edit",
    defaultShortcut: "Ctrl+C",
    alternativeShortcuts: ["Cmd+C"],
    scope: "global",
    icon: "Copy",
    keywords: ["copy", "clipboard"],
  },
  {
    id: "edit.cut",
    label: "Cut Selected Item",
    description: "Cut selected item and place on clipboard",
    category: "Edit",
    defaultShortcut: "Ctrl+X",
    alternativeShortcuts: ["Cmd+X"],
    scope: "global",
    icon: "Scissors",
    keywords: ["cut", "remove"],
  },
  {
    id: "edit.paste",
    label: "Paste Item / Page",
    description: "Paste copied item or page from clipboard into document",
    category: "Edit",
    defaultShortcut: "Ctrl+V",
    alternativeShortcuts: ["Cmd+V"],
    scope: "global",
    icon: "Clipboard",
    keywords: ["paste", "insert"],
  },
  {
    id: "edit.duplicate",
    label: "Duplicate Selected Item / Page",
    description: "Clone active page or selected canvas element",
    category: "Edit",
    defaultShortcut: "Ctrl+D",
    alternativeShortcuts: ["Cmd+D"],
    scope: "global",
    icon: "CopyPlus",
    keywords: ["duplicate", "clone", "replicate"],
  },
  {
    id: "edit.delete",
    label: "Delete Active Page / Item",
    description: "Remove the selected page or element from the document",
    category: "Edit",
    defaultShortcut: "Delete",
    alternativeShortcuts: ["Backspace"],
    scope: "global",
    icon: "Trash2",
    keywords: ["delete", "remove", "trash", "discard"],
  },
  {
    id: "edit.selectAll",
    label: "Select All Pages",
    description: "Select all pages in the current document",
    category: "Edit",
    defaultShortcut: "Ctrl+A",
    alternativeShortcuts: ["Cmd+A"],
    scope: "global",
    icon: "CheckSquare",
    keywords: ["select all", "highlight all"],
  },
  {
    id: "edit.deselectAll",
    label: "Deselect All Pages",
    description: "Clear current page selection",
    category: "Edit",
    defaultShortcut: "Ctrl+Shift+A",
    alternativeShortcuts: ["Cmd+Shift+A"],
    scope: "global",
    icon: "Square",
    keywords: ["deselect", "clear selection", "unselect"],
  },

  // ==========================================
  // 3. GLOBAL UI, COMMAND PALETTE & SHORTCUTS HELP
  // ==========================================
  {
    id: "app.commandPalette",
    label: "Command Palette",
    description: "Open the searchable global action palette",
    category: "Global",
    defaultShortcut: "Ctrl+K",
    alternativeShortcuts: ["Cmd+K", "Ctrl+Shift+P", "Cmd+Shift+P"],
    scope: "global",
    allowInInputs: true,
    icon: "Command",
    keywords: ["command", "palette", "quick action", "search", "spotlight"],
  },
  {
    id: "app.shortcutHelp",
    label: "Keyboard Shortcuts & Settings",
    description: "View, customize, and configure keyboard shortcuts",
    category: "Global",
    defaultShortcut: "Ctrl+/",
    alternativeShortcuts: ["Cmd+/", "F1"],
    scope: "global",
    allowInInputs: true,
    icon: "Keyboard",
    keywords: ["shortcuts", "hotkeys", "help", "keybindings", "customize"],
  },
  {
    id: "app.escape",
    label: "Escape / Cancel Operation",
    description: "Close top modal, dismiss palette, or exit active crop/tool",
    category: "Global",
    defaultShortcut: "Escape",
    scope: "global",
    allowInInputs: true,
    priority: 100,
    icon: "X",
    keywords: ["cancel", "escape", "dismiss", "exit"],
  },
  {
    id: "app.confirm",
    label: "Confirm / Apply Operation",
    description: "Confirm active dialog or apply pending changes",
    category: "Global",
    defaultShortcut: "Enter",
    scope: "global",
    icon: "Check",
    keywords: ["confirm", "ok", "apply", "enter"],
  },
  {
    id: "app.search",
    label: "Find in Document / OCR Search",
    description: "Search text across OCR layers and metadata",
    category: "Global",
    defaultShortcut: "Ctrl+F",
    alternativeShortcuts: ["Cmd+F"],
    scope: "global",
    icon: "Search",
    keywords: ["search", "find", "ocr search", "query"],
  },
  {
    id: "app.diagnostics",
    label: "System Diagnostics & Telemetry",
    description: "Display engine telemetry, memory consumption, and canvas stats",
    category: "Global",
    defaultShortcut: "Ctrl+Shift+D",
    alternativeShortcuts: ["Cmd+Shift+D"],
    scope: "global",
    icon: "Activity",
    keywords: ["diagnostics", "telemetry", "memory", "perf", "debug"],
  },

  // ==========================================
  // 4. TOOL ACTIVATION (CANVAS TOOLS)
  // ==========================================
  {
    id: "tool.select",
    label: "Selection Tool (V)",
    description: "Switch to pointer selection and interaction mode",
    category: "Tools",
    defaultShortcut: "V",
    scope: "canvas",
    icon: "MousePointer",
    keywords: ["select", "pointer", "cursor", "arrow"],
  },
  {
    id: "tool.pan",
    label: "Hand / Pan Tool (H)",
    description: "Switch to canvas panning hand tool",
    category: "Tools",
    defaultShortcut: "H",
    scope: "canvas",
    icon: "Hand",
    keywords: ["pan", "hand", "drag", "move canvas"],
  },
  {
    id: "tool.crop",
    label: "Dedicated Page Crop Tool (C)",
    description: "Activate precision 8-point physical crop overlay",
    category: "Tools",
    defaultShortcut: "C",
    scope: "canvas",
    icon: "Crop",
    keywords: ["crop", "trim", "cut margins", "bounds"],
  },
  {
    id: "tool.magnifier",
    label: "Magnifier Zoom Tool (Z)",
    description: "Activate precision circular loupe magnifier",
    category: "Tools",
    defaultShortcut: "Z",
    scope: "canvas",
    icon: "ZoomIn",
    keywords: ["magnifier", "loupe", "zoom lens", "inspection"],
  },
  {
    id: "tool.text",
    label: "Text Annotation Tool (T)",
    description: "Add editable typography annotations to page",
    category: "Tools",
    defaultShortcut: "T",
    scope: "canvas",
    icon: "Type",
    keywords: ["text", "annotate", "type", "font"],
  },
  {
    id: "tool.highlight",
    label: "Highlighter Tool (5)",
    description: "Highlight text and areas on the document",
    category: "Tools",
    defaultShortcut: "5",
    scope: "canvas",
    icon: "Highlighter",
    keywords: ["highlight", "marker", "fluorescent"],
  },
  {
    id: "tool.freehand",
    label: "Freehand Pen Tool (6)",
    description: "Draw freehand ink markup with smooth Bézier strokes",
    category: "Tools",
    defaultShortcut: "6",
    scope: "canvas",
    icon: "PenTool",
    keywords: ["pen", "draw", "ink", "freehand", "sketch"],
  },
  {
    id: "tool.rect",
    label: "Rectangle Shape Tool (1)",
    description: "Draw rectangular boxes and visual callouts",
    category: "Tools",
    defaultShortcut: "1",
    scope: "canvas",
    icon: "Square",
    keywords: ["rectangle", "box", "shape"],
  },
  {
    id: "tool.circle",
    label: "Circle Shape Tool (2)",
    description: "Draw circular and elliptical focus frames",
    category: "Tools",
    defaultShortcut: "2",
    scope: "canvas",
    icon: "Circle",
    keywords: ["circle", "ellipse", "oval"],
  },
  {
    id: "tool.arrow",
    label: "Arrow Shape Tool (3)",
    description: "Draw directional pointer arrows",
    category: "Tools",
    defaultShortcut: "3",
    scope: "canvas",
    icon: "ArrowRight",
    keywords: ["arrow", "pointer", "indicator"],
  },
  {
    id: "tool.stamp",
    label: "Stamp Tool (4)",
    description: "Apply Approved, Confidential, or custom stamps",
    category: "Tools",
    defaultShortcut: "4",
    scope: "canvas",
    icon: "Stamp",
    keywords: ["stamp", "approved", "confidential", "watermark"],
  },
  {
    id: "tool.redact",
    label: "Redact Region Tool (X)",
    description: "Draw permanent blackout or redaction zones",
    category: "Tools",
    defaultShortcut: "X",
    scope: "canvas",
    icon: "ShieldAlert",
    keywords: ["redact", "blackout", "censor", "sanitize", "privacy"],
  },
  {
    id: "tool.splitView",
    label: "Split-View Compare Tool (G)",
    description: "Interactive before/after split slider across filters",
    category: "Tools",
    defaultShortcut: "G",
    scope: "canvas",
    icon: "SplitSquareVertical",
    keywords: ["split", "before after", "slider", "compare filter"],
  },

  // ==========================================
  // 5. STUDIOS & WORKSPACES LAUNCH
  // ==========================================
  {
    id: "studio.filters",
    label: "CamScanner Filter Studio",
    description: "Launch 16-preset document enhancement studio",
    category: "View",
    defaultShortcut: "F",
    scope: "global",
    icon: "Palette",
    keywords: ["filters", "camscanner", "magic color", "bw", "presets"],
  },
  {
    id: "studio.photoPrint",
    label: "4×6\" Photo & Passport Studio",
    description: "Launch 4×6 photo printing & biometric passport studio",
    category: "View",
    defaultShortcut: "P",
    scope: "global",
    icon: "Printer",
    keywords: ["photo", "passport", "4x6", "print studio", "biometric"],
  },
  {
    id: "studio.idCard",
    label: "ID Card / CNIC Print Studio",
    description: "Launch dual-sided ID Card / CNIC A4 multi-copy print studio",
    category: "View",
    defaultShortcut: "I",
    scope: "global",
    icon: "CreditCard",
    keywords: ["id card", "cnic", "badge", "front back", "print studio"],
  },
  {
    id: "studio.cardDesigner",
    label: "ID & Service Card Designer (Vector)",
    description: "Launch professional CorelDRAW-inspired vector ID & service card designer",
    category: "View",
    defaultShortcut: "D",
    scope: "global",
    icon: "Sparkles",
    keywords: ["card designer", "service card", "employee card", "vector", "coreldraw", "badge designer", "id"],
  },
  {
    id: "studio.a6HalfCard",
    label: "A6 Half-Card Layout Studio",
    description: "Launch 74×105mm A6 half-card layout studio",
    category: "View",
    defaultShortcut: "A",
    scope: "global",
    icon: "Layers",
    keywords: ["a6", "half card", "card layout", "74x105"],
  },
  {
    id: "studio.batch",
    label: "Batch Automation Studio",
    description: "Run multi-page deskew, OCR, and cleanup pipeline",
    category: "Batch & Intelligence",
    defaultShortcut: "B",
    scope: "global",
    icon: "Layers",
    keywords: ["batch", "automation", "pipeline", "multi-page"],
  },
  {
    id: "studio.compare",
    label: "Document Comparison Studio",
    description: "Visual diff and side-by-side comparison",
    category: "View",
    defaultShortcut: "M",
    scope: "global",
    icon: "SplitSquareVertical",
    keywords: ["compare", "diff", "difference", "visual diff"],
  },
  {
    id: "studio.security",
    label: "Document Security & Redaction",
    description: "AES encryption, metadata stripping, and sanitization",
    category: "Security",
    defaultShortcut: "Shift+X",
    scope: "global",
    icon: "ShieldCheck",
    keywords: ["security", "encrypt", "password", "metadata", "sanitize"],
  },
  {
    id: "studio.splitPdf",
    label: "Split PDF Studio",
    description: "Extract pages or split PDF into separate files",
    category: "File",
    defaultShortcut: "Shift+S",
    scope: "global",
    icon: "Scissors",
    keywords: ["split", "extract pages", "divide pdf"],
  },
  {
    id: "studio.autoDeskew",
    label: "Auto-Deskew & Align",
    description: "Compute orientation angle and deskew active page",
    category: "Batch & Intelligence",
    defaultShortcut: "Shift+D",
    scope: "global",
    icon: "Wand2",
    keywords: ["deskew", "straighten", "align", "rotate auto"],
  },
  {
    id: "studio.autoCrop",
    label: "Auto-Detect Document Margins",
    description: "Automatically detect paper edges and crop to borders",
    category: "Batch & Intelligence",
    defaultShortcut: "Shift+C",
    scope: "global",
    icon: "Crop",
    keywords: ["auto crop", "detect edges", "corners", "page boundary"],
  },
  {
    id: "studio.ocr",
    label: "Run Multi-Language OCR",
    description: "Execute local optical character recognition engine",
    category: "Batch & Intelligence",
    defaultShortcut: "O",
    scope: "global",
    icon: "FileSearch",
    keywords: ["ocr", "text recognition", "tesseract", "searchable"],
  },
  {
    id: "studio.intelligence",
    label: "Document Intelligence Analysis",
    description: "Classify document and extract structured entities",
    category: "Batch & Intelligence",
    defaultShortcut: "D",
    scope: "global",
    icon: "Sparkles",
    keywords: ["ai", "intelligence", "classification", "entities", "gemini"],
  },

  // ==========================================
  // 6. PDF NAVIGATION & PAGE MANAGEMENT
  // ==========================================
  {
    id: "pdf.nextPage",
    label: "Next Page",
    description: "Advance to the next page in the active document",
    category: "Navigation",
    defaultShortcut: "PageDown",
    scope: "global",
    icon: "ChevronDown",
    keywords: ["next", "page down", "forward"],
  },
  {
    id: "pdf.prevPage",
    label: "Previous Page",
    description: "Return to the previous page in the active document",
    category: "Navigation",
    defaultShortcut: "PageUp",
    scope: "global",
    icon: "ChevronUp",
    keywords: ["prev", "previous", "page up", "back"],
  },
  {
    id: "pdf.firstPage",
    label: "First Page",
    description: "Jump to the first page of the document",
    category: "Navigation",
    defaultShortcut: "Home",
    alternativeShortcuts: ["Ctrl+Home", "Cmd+Home"],
    scope: "global",
    icon: "ArrowUpToLine",
    keywords: ["first page", "home", "start"],
  },
  {
    id: "pdf.lastPage",
    label: "Last Page",
    description: "Jump to the last page of the document",
    category: "Navigation",
    defaultShortcut: "End",
    alternativeShortcuts: ["Ctrl+End", "Cmd+End"],
    scope: "global",
    icon: "ArrowDownToLine",
    keywords: ["last page", "end"],
  },
  {
    id: "pdf.rotateCw",
    label: "Rotate Page 90° Clockwise",
    description: "Rotate active page orientation 90 degrees right",
    category: "PDF",
    defaultShortcut: "R",
    scope: "global",
    icon: "RotateCw",
    keywords: ["rotate", "cw", "clockwise", "turn right"],
  },
  {
    id: "pdf.rotateCcw",
    label: "Rotate Page 90° Counter-Clockwise",
    description: "Rotate active page orientation 90 degrees left",
    category: "PDF",
    defaultShortcut: "Shift+R",
    scope: "global",
    icon: "RotateCcw",
    keywords: ["rotate ccw", "counter-clockwise", "turn left"],
  },
  {
    id: "pdf.addBlank",
    label: "Insert Blank Page",
    description: "Append a blank page to the current document",
    category: "PDF",
    defaultShortcut: "Ctrl+Shift+N",
    alternativeShortcuts: ["Cmd+Shift+N"],
    scope: "global",
    icon: "Plus",
    keywords: ["blank page", "insert page", "new page"],
  },
  {
    id: "pdf.moveUp",
    label: "Move Page Upward",
    description: "Shift current page up in the page sequence",
    category: "PDF",
    defaultShortcut: "Ctrl+Shift+Up",
    alternativeShortcuts: ["Cmd+Shift+Up"],
    scope: "global",
    icon: "MoveUp",
    keywords: ["move page up", "reorder"],
  },
  {
    id: "pdf.moveDown",
    label: "Move Page Downward",
    description: "Shift current page down in the page sequence",
    category: "PDF",
    defaultShortcut: "Ctrl+Shift+Down",
    alternativeShortcuts: ["Cmd+Shift+Down"],
    scope: "global",
    icon: "MoveDown",
    keywords: ["move page down", "reorder"],
  },
  {
    id: "pdf.toggleThumbnails",
    label: "Toggle Page Thumbnails Sidebar",
    description: "Show or hide the page thumbnail strip",
    category: "Navigation",
    defaultShortcut: "Ctrl+B",
    alternativeShortcuts: ["Cmd+B"],
    scope: "global",
    icon: "Sidebar",
    keywords: ["thumbnails", "sidebar", "pages"],
  },
  {
    id: "pdf.goToPage",
    label: "Go to Page...",
    description: "Jump directly to specific page index",
    category: "Navigation",
    defaultShortcut: "Ctrl+G",
    alternativeShortcuts: ["Cmd+G", "Ctrl+L", "Cmd+L"],
    scope: "global",
    icon: "Hash",
    keywords: ["go to page", "jump", "page number"],
  },

  // ==========================================
  // 7. VIEWPORT & ZOOM SHORTCUTS
  // ==========================================
  {
    id: "view.zoomIn",
    label: "Zoom In (+)",
    description: "Increase viewport zoom level",
    category: "View",
    defaultShortcut: "+",
    alternativeShortcuts: ["=", "Ctrl+Plus", "Cmd+Plus"],
    scope: "global",
    icon: "ZoomIn",
    keywords: ["zoom in", "enlarge", "plus"],
  },
  {
    id: "view.zoomOut",
    label: "Zoom Out (-)",
    description: "Decrease viewport zoom level",
    category: "View",
    defaultShortcut: "-",
    alternativeShortcuts: ["Ctrl+Minus", "Cmd+Minus"],
    scope: "global",
    icon: "ZoomOut",
    keywords: ["zoom out", "shrink", "minus"],
  },
  {
    id: "view.fitPage",
    label: "Fit Page (0)",
    description: "Scale page to fit entirely within viewport",
    category: "View",
    defaultShortcut: "0",
    alternativeShortcuts: ["Ctrl+0", "Cmd+0"],
    scope: "global",
    icon: "Maximize",
    keywords: ["fit page", "reset zoom", "fit to screen"],
  },
  {
    id: "view.actualSize",
    label: "Actual Size / 100% (Ctrl+1)",
    description: "Render document at exact 100% physical scale",
    category: "View",
    defaultShortcut: "Ctrl+1",
    alternativeShortcuts: ["Cmd+1"],
    scope: "global",
    icon: "Maximize2",
    keywords: ["100%", "actual size", "original scale"],
  },
  {
    id: "view.fitWidth",
    label: "Fit Width (Ctrl+2)",
    description: "Scale document to match window width",
    category: "View",
    defaultShortcut: "Ctrl+2",
    alternativeShortcuts: ["Cmd+2"],
    scope: "global",
    icon: "Minimize2",
    keywords: ["fit width", "page width"],
  },
  {
    id: "view.fitHeight",
    label: "Fit Height (Ctrl+3)",
    description: "Scale document to match window height",
    category: "View",
    defaultShortcut: "Ctrl+3",
    alternativeShortcuts: ["Cmd+3"],
    scope: "global",
    icon: "Maximize2",
    keywords: ["fit height", "page height"],
  },

  // ==========================================
  // 8. CROP MODE COMMANDS (SCOPE: CROP)
  // ==========================================
  {
    id: "crop.apply",
    label: "Apply Crop (Enter)",
    description: "Commit page crop and recalculate boundaries",
    category: "Crop",
    defaultShortcut: "Enter",
    scope: "crop",
    priority: 20,
    icon: "Check",
    keywords: ["apply crop", "commit", "save crop"],
  },
  {
    id: "crop.cancel",
    label: "Cancel Crop (Escape)",
    description: "Exit crop mode without saving changes",
    category: "Crop",
    defaultShortcut: "Escape",
    scope: "crop",
    priority: 20,
    allowInInputs: true,
    icon: "X",
    keywords: ["cancel crop", "exit crop"],
  },
  {
    id: "crop.reset",
    label: "Reset Crop Box (R)",
    description: "Reset crop box to full page boundaries",
    category: "Crop",
    defaultShortcut: "R",
    scope: "crop",
    priority: 20,
    icon: "RotateCcw",
    keywords: ["reset crop", "clear crop"],
  },
  {
    id: "crop.nudgeUp",
    label: "Nudge Crop Up (↑)",
    description: "Move crop box up by 1% increment",
    category: "Crop",
    defaultShortcut: "ArrowUp",
    scope: "crop",
    priority: 20,
    keywords: ["crop up", "nudge"],
  },
  {
    id: "crop.nudgeDown",
    label: "Nudge Crop Down (↓)",
    description: "Move crop box down by 1% increment",
    category: "Crop",
    defaultShortcut: "ArrowDown",
    scope: "crop",
    priority: 20,
    keywords: ["crop down", "nudge"],
  },
  {
    id: "crop.nudgeLeft",
    label: "Nudge Crop Left (←)",
    description: "Move crop box left by 1% increment",
    category: "Crop",
    defaultShortcut: "ArrowLeft",
    scope: "crop",
    priority: 20,
    keywords: ["crop left", "nudge"],
  },
  {
    id: "crop.nudgeRight",
    label: "Nudge Crop Right (→)",
    description: "Move crop box right by 1% increment",
    category: "Crop",
    defaultShortcut: "ArrowRight",
    scope: "crop",
    priority: 20,
    keywords: ["crop right", "nudge"],
  },
  {
    id: "crop.largeNudgeUp",
    label: "Large Nudge Crop Up (Shift+↑)",
    description: "Move crop box up by 5% increment",
    category: "Crop",
    defaultShortcut: "Shift+ArrowUp",
    scope: "crop",
    priority: 20,
    keywords: ["crop up fast"],
  },
  {
    id: "crop.largeNudgeDown",
    label: "Large Nudge Crop Down (Shift+↓)",
    description: "Move crop box down by 5% increment",
    category: "Crop",
    defaultShortcut: "Shift+ArrowDown",
    scope: "crop",
    priority: 20,
    keywords: ["crop down fast"],
  },
  {
    id: "crop.largeNudgeLeft",
    label: "Large Nudge Crop Left (Shift+←)",
    description: "Move crop box left by 5% increment",
    category: "Crop",
    defaultShortcut: "Shift+ArrowLeft",
    scope: "crop",
    priority: 20,
    keywords: ["crop left fast"],
  },
  {
    id: "crop.largeNudgeRight",
    label: "Large Nudge Crop Right (Shift+→)",
    description: "Move crop box right by 5% increment",
    category: "Crop",
    defaultShortcut: "Shift+ArrowRight",
    scope: "crop",
    priority: 20,
    keywords: ["crop right fast"],
  },
  {
    id: "crop.fineNudgeUp",
    label: "Fine Nudge Crop Up (Alt+↑)",
    description: "Fine micro-adjust crop box up by 0.2% increment",
    category: "Crop",
    defaultShortcut: "Alt+ArrowUp",
    scope: "crop",
    priority: 20,
    keywords: ["crop up fine"],
  },
  {
    id: "crop.fineNudgeDown",
    label: "Fine Nudge Crop Down (Alt+↓)",
    description: "Fine micro-adjust crop box down by 0.2% increment",
    category: "Crop",
    defaultShortcut: "Alt+ArrowDown",
    scope: "crop",
    priority: 20,
    keywords: ["crop down fine"],
  },
  {
    id: "crop.fineNudgeLeft",
    label: "Fine Nudge Crop Left (Alt+←)",
    description: "Fine micro-adjust crop box left by 0.2% increment",
    category: "Crop",
    defaultShortcut: "Alt+ArrowLeft",
    scope: "crop",
    priority: 20,
    keywords: ["crop left fine"],
  },
  {
    id: "crop.fineNudgeRight",
    label: "Fine Nudge Crop Right (Alt+→)",
    description: "Fine micro-adjust crop box right by 0.2% increment",
    category: "Crop",
    defaultShortcut: "Alt+ArrowRight",
    scope: "crop",
    priority: 20,
    keywords: ["crop right fine"],
  },

  // ==========================================
  // 9. PASSPORT PHOTO STUDIO COMMANDS
  // ==========================================
  {
    id: "photo.zoomIn",
    label: "Photo Zoom In (+)",
    description: "Increase portrait zoom scale within framing oval",
    category: "Passport Studio",
    defaultShortcut: "+",
    alternativeShortcuts: ["="],
    scope: "photo-studio",
    priority: 15,
    icon: "ZoomIn",
    keywords: ["photo zoom in"],
  },
  {
    id: "photo.zoomOut",
    label: "Photo Zoom Out (-)",
    description: "Decrease portrait zoom scale within framing oval",
    category: "Passport Studio",
    defaultShortcut: "-",
    scope: "photo-studio",
    priority: 15,
    icon: "ZoomOut",
    keywords: ["photo zoom out"],
  },
  {
    id: "photo.resetZoom",
    label: "Reset Photo Zoom (0)",
    description: "Reset photo zoom to 1.0 fit level",
    category: "Passport Studio",
    defaultShortcut: "0",
    scope: "photo-studio",
    priority: 15,
    icon: "Maximize",
    keywords: ["photo reset zoom"],
  },
  {
    id: "photo.rotateCw",
    label: "Rotate Photo Clockwise (R)",
    description: "Rotate photo 90 degrees clockwise",
    category: "Passport Studio",
    defaultShortcut: "R",
    scope: "photo-studio",
    priority: 15,
    icon: "RotateCw",
    keywords: ["photo rotate cw"],
  },
  {
    id: "photo.rotateCcw",
    label: "Rotate Photo Counter-Clockwise (Shift+R)",
    description: "Rotate photo 90 degrees counter-clockwise",
    category: "Passport Studio",
    defaultShortcut: "Shift+R",
    scope: "photo-studio",
    priority: 15,
    icon: "RotateCcw",
    keywords: ["photo rotate ccw"],
  },
  {
    id: "photo.nudgeUp",
    label: "Pan Photo Up (↑)",
    description: "Pan portrait upward within biometric framing box",
    category: "Passport Studio",
    defaultShortcut: "ArrowUp",
    scope: "photo-studio",
    priority: 15,
    keywords: ["pan photo up"],
  },
  {
    id: "photo.nudgeDown",
    label: "Pan Photo Down (↓)",
    description: "Pan portrait downward within biometric framing box",
    category: "Passport Studio",
    defaultShortcut: "ArrowDown",
    scope: "photo-studio",
    priority: 15,
    keywords: ["pan photo down"],
  },
  {
    id: "photo.nudgeLeft",
    label: "Pan Photo Left (←)",
    description: "Pan portrait left within biometric framing box",
    category: "Passport Studio",
    defaultShortcut: "ArrowLeft",
    scope: "photo-studio",
    priority: 15,
    keywords: ["pan photo left"],
  },
  {
    id: "photo.nudgeRight",
    label: "Pan Photo Right (→)",
    description: "Pan portrait right within biometric framing box",
    category: "Passport Studio",
    defaultShortcut: "ArrowRight",
    scope: "photo-studio",
    priority: 15,
    keywords: ["pan photo right"],
  },
  {
    id: "photo.toggleGrid",
    label: "Toggle Alignment Grid (G)",
    description: "Toggle rule-of-thirds and alignment grid on photo canvas",
    category: "Passport Studio",
    defaultShortcut: "G",
    scope: "photo-studio",
    priority: 15,
    icon: "Grid",
    keywords: ["grid", "alignment"],
  },
  {
    id: "photo.toggleGuides",
    label: "Toggle Cutting Guides (T)",
    description: "Toggle physical printed cutting corner marks and trim guides",
    category: "Passport Studio",
    defaultShortcut: "T",
    scope: "photo-studio",
    priority: 15,
    icon: "Scissors",
    keywords: ["cutting guides", "trim marks"],
  },
  {
    id: "photo.resetAll",
    label: "Reset All Photo Adjustments",
    description: "Reset zoom, position, and filter values to pristine defaults",
    category: "Passport Studio",
    defaultShortcut: "Ctrl+Shift+R",
    alternativeShortcuts: ["Cmd+Shift+R"],
    scope: "photo-studio",
    priority: 15,
    icon: "RefreshCw",
    keywords: ["reset photo", "revert photo"],
  },
  {
    id: "photo.print",
    label: "Print Photo Sheet (Ctrl+P)",
    description: "Print 4×6 photo sheet with color-calibrated layout",
    category: "Passport Studio",
    defaultShortcut: "Ctrl+P",
    alternativeShortcuts: ["Cmd+P"],
    scope: "photo-studio",
    priority: 15,
    icon: "Printer",
    keywords: ["print 4x6"],
  },
  {
    id: "photo.export",
    label: "Export 4×6 High-DPI PDF (Ctrl+E)",
    description: "Export full 300+ DPI PDF ready for photo-lab printing",
    category: "Passport Studio",
    defaultShortcut: "Ctrl+E",
    alternativeShortcuts: ["Cmd+E"],
    scope: "photo-studio",
    priority: 15,
    icon: "Download",
    keywords: ["export 4x6"],
  },
  {
    id: "photo.close",
    label: "Close Photo Studio (Escape)",
    description: "Exit Passport & Photo Studio workspace",
    category: "Passport Studio",
    defaultShortcut: "Escape",
    scope: "photo-studio",
    priority: 15,
    allowInInputs: true,
    icon: "X",
    keywords: ["close photo studio"],
  },

  // ==========================================
  // 10. ID CARD / CNIC STUDIO COMMANDS
  // ==========================================
  {
    id: "idcard.switchFront",
    label: "Switch to Front Side (1)",
    description: "Activate Front side of ID card for adjustments and viewing",
    category: "ID Card Studio",
    defaultShortcut: "1",
    alternativeShortcuts: ["F"],
    scope: "idcard-studio",
    priority: 15,
    icon: "CreditCard",
    keywords: ["front side", "id front", "switch front"],
  },
  {
    id: "idcard.switchBack",
    label: "Switch to Back Side (2)",
    description: "Activate Back side of ID card for adjustments and viewing",
    category: "ID Card Studio",
    defaultShortcut: "2",
    alternativeShortcuts: ["B"],
    scope: "idcard-studio",
    priority: 15,
    icon: "CreditCard",
    keywords: ["back side", "id back", "switch back"],
  },
  {
    id: "idcard.toggleBoth",
    label: "Toggle Both Sides View (3)",
    description: "Toggle side-by-side display of both Front & Back card sides",
    category: "ID Card Studio",
    defaultShortcut: "3",
    alternativeShortcuts: ["S"],
    scope: "idcard-studio",
    priority: 15,
    icon: "Layers",
    keywords: ["both sides", "front and back"],
  },
  {
    id: "idcard.zoomIn",
    label: "ID Card Zoom In (+)",
    description: "Zoom in on active ID card canvas",
    category: "ID Card Studio",
    defaultShortcut: "+",
    alternativeShortcuts: ["="],
    scope: "idcard-studio",
    priority: 15,
    icon: "ZoomIn",
    keywords: ["id zoom in"],
  },
  {
    id: "idcard.zoomOut",
    label: "ID Card Zoom Out (-)",
    description: "Zoom out on active ID card canvas",
    category: "ID Card Studio",
    defaultShortcut: "-",
    scope: "idcard-studio",
    priority: 15,
    icon: "ZoomOut",
    keywords: ["id zoom out"],
  },
  {
    id: "idcard.resetZoom",
    label: "Reset ID Card Zoom (0)",
    description: "Reset zoom to default sheet scale",
    category: "ID Card Studio",
    defaultShortcut: "0",
    scope: "idcard-studio",
    priority: 15,
    icon: "Maximize",
    keywords: ["id reset zoom"],
  },
  {
    id: "idcard.rotateCw",
    label: "Rotate ID Card Clockwise (R)",
    description: "Rotate active card side 90 degrees clockwise",
    category: "ID Card Studio",
    defaultShortcut: "R",
    scope: "idcard-studio",
    priority: 15,
    icon: "RotateCw",
    keywords: ["id rotate cw"],
  },
  {
    id: "idcard.rotateCcw",
    label: "Rotate ID Card Counter-Clockwise (Shift+R)",
    description: "Rotate active card side 90 degrees counter-clockwise",
    category: "ID Card Studio",
    defaultShortcut: "Shift+R",
    scope: "idcard-studio",
    priority: 15,
    icon: "RotateCcw",
    keywords: ["id rotate ccw"],
  },
  {
    id: "idcard.nudgeUp",
    label: "Nudge Card Up (↑)",
    description: "Nudge active card image upward within its slot",
    category: "ID Card Studio",
    defaultShortcut: "ArrowUp",
    scope: "idcard-studio",
    priority: 15,
    keywords: ["nudge card up"],
  },
  {
    id: "idcard.nudgeDown",
    label: "Nudge Card Down (↓)",
    description: "Nudge active card image downward within its slot",
    category: "ID Card Studio",
    defaultShortcut: "ArrowDown",
    scope: "idcard-studio",
    priority: 15,
    keywords: ["nudge card down"],
  },
  {
    id: "idcard.nudgeLeft",
    label: "Nudge Card Left (←)",
    description: "Nudge active card image left within its slot",
    category: "ID Card Studio",
    defaultShortcut: "ArrowLeft",
    scope: "idcard-studio",
    priority: 15,
    keywords: ["nudge card left"],
  },
  {
    id: "idcard.nudgeRight",
    label: "Nudge Card Right (→)",
    description: "Nudge active card image right within its slot",
    category: "ID Card Studio",
    defaultShortcut: "ArrowRight",
    scope: "idcard-studio",
    priority: 15,
    keywords: ["nudge card right"],
  },
  {
    id: "idcard.toggleGrid",
    label: "Toggle ID Grid (G)",
    description: "Toggle layout alignment grid",
    category: "ID Card Studio",
    defaultShortcut: "G",
    scope: "idcard-studio",
    priority: 15,
    icon: "Grid",
    keywords: ["id grid"],
  },
  {
    id: "idcard.toggleGuides",
    label: "Toggle Cutting Guides (T)",
    description: "Toggle printed cutting marks and border guides",
    category: "ID Card Studio",
    defaultShortcut: "T",
    scope: "idcard-studio",
    priority: 15,
    icon: "Scissors",
    keywords: ["id cutting guides"],
  },
  {
    id: "idcard.resetAll",
    label: "Reset ID Card Adjustments",
    description: "Reset zoom, position, and filter values for active side",
    category: "ID Card Studio",
    defaultShortcut: "Ctrl+Shift+R",
    alternativeShortcuts: ["Cmd+Shift+R"],
    scope: "idcard-studio",
    priority: 15,
    icon: "RefreshCw",
    keywords: ["reset id adjustments"],
  },
  {
    id: "idcard.print",
    label: "Print ID Card Sheet (Ctrl+P)",
    description: "Send multi-copy ID sheet to physical printer",
    category: "ID Card Studio",
    defaultShortcut: "Ctrl+P",
    alternativeShortcuts: ["Cmd+P"],
    scope: "idcard-studio",
    priority: 15,
    icon: "Printer",
    keywords: ["print id"],
  },
  {
    id: "idcard.export",
    label: "Export ID Card Sheet (Ctrl+E)",
    description: "Export high-resolution PDF of ID layout sheet",
    category: "ID Card Studio",
    defaultShortcut: "Ctrl+E",
    alternativeShortcuts: ["Cmd+E"],
    scope: "idcard-studio",
    priority: 15,
    icon: "Download",
    keywords: ["export id"],
  },
  {
    id: "idcard.close",
    label: "Close ID Card Studio (Escape)",
    description: "Exit ID Card & CNIC Studio workspace",
    category: "ID Card Studio",
    defaultShortcut: "Escape",
    scope: "idcard-studio",
    priority: 15,
    allowInInputs: true,
    icon: "X",
    keywords: ["close id studio"],
  },

  // ==========================================
  // 11. A6 HALF-CARD STUDIO COMMANDS
  // ==========================================
  {
    id: "a6.switchFront",
    label: "Switch to Front Card (1)",
    description: "Select front card in A6 studio",
    category: "A6 Studio",
    defaultShortcut: "1",
    alternativeShortcuts: ["F"],
    scope: "a6-studio",
    priority: 15,
    icon: "Layers",
    keywords: ["a6 front"],
  },
  {
    id: "a6.switchBack",
    label: "Switch to Back Card (2)",
    description: "Select back card in A6 studio",
    category: "A6 Studio",
    defaultShortcut: "2",
    alternativeShortcuts: ["B"],
    scope: "a6-studio",
    priority: 15,
    icon: "Layers",
    keywords: ["a6 back"],
  },
  {
    id: "a6.toggleOrientation",
    label: "Toggle Portrait / Landscape (P)",
    description: "Switch A6 paper sheet between portrait and landscape",
    category: "A6 Studio",
    defaultShortcut: "P",
    scope: "a6-studio",
    priority: 15,
    icon: "RefreshCw",
    keywords: ["orientation", "portrait", "landscape"],
  },
  {
    id: "a6.zoomIn",
    label: "A6 Zoom In (+)",
    description: "Zoom in on A6 layout sheet",
    category: "A6 Studio",
    defaultShortcut: "+",
    alternativeShortcuts: ["="],
    scope: "a6-studio",
    priority: 15,
    icon: "ZoomIn",
    keywords: ["a6 zoom in"],
  },
  {
    id: "a6.zoomOut",
    label: "A6 Zoom Out (-)",
    description: "Zoom out on A6 layout sheet",
    category: "A6 Studio",
    defaultShortcut: "-",
    scope: "a6-studio",
    priority: 15,
    icon: "ZoomOut",
    keywords: ["a6 zoom out"],
  },
  {
    id: "a6.resetZoom",
    label: "Reset A6 Zoom (0)",
    description: "Reset A6 zoom to 100% fit",
    category: "A6 Studio",
    defaultShortcut: "0",
    scope: "a6-studio",
    priority: 15,
    icon: "Maximize",
    keywords: ["a6 reset zoom"],
  },
  {
    id: "a6.rotateCw",
    label: "Rotate A6 Card Clockwise (R)",
    description: "Rotate active card 90 degrees clockwise",
    category: "A6 Studio",
    defaultShortcut: "R",
    scope: "a6-studio",
    priority: 15,
    icon: "RotateCw",
    keywords: ["a6 rotate cw"],
  },
  {
    id: "a6.rotateCcw",
    label: "Rotate A6 Card Counter-Clockwise (Shift+R)",
    description: "Rotate active card 90 degrees counter-clockwise",
    category: "A6 Studio",
    defaultShortcut: "Shift+R",
    scope: "a6-studio",
    priority: 15,
    icon: "RotateCcw",
    keywords: ["a6 rotate ccw"],
  },
  {
    id: "a6.nudgeUp",
    label: "Nudge Card Up (↑)",
    description: "Nudge active card image upward",
    category: "A6 Studio",
    defaultShortcut: "ArrowUp",
    scope: "a6-studio",
    priority: 15,
    keywords: ["a6 nudge up"],
  },
  {
    id: "a6.nudgeDown",
    label: "Nudge Card Down (↓)",
    description: "Nudge active card image downward",
    category: "A6 Studio",
    defaultShortcut: "ArrowDown",
    scope: "a6-studio",
    priority: 15,
    keywords: ["a6 nudge down"],
  },
  {
    id: "a6.nudgeLeft",
    label: "Nudge Card Left (←)",
    description: "Nudge active card image left",
    category: "A6 Studio",
    defaultShortcut: "ArrowLeft",
    scope: "a6-studio",
    priority: 15,
    keywords: ["a6 nudge left"],
  },
  {
    id: "a6.nudgeRight",
    label: "Nudge Card Right (→)",
    description: "Nudge active card image right",
    category: "A6 Studio",
    defaultShortcut: "ArrowRight",
    scope: "a6-studio",
    priority: 15,
    keywords: ["a6 nudge right"],
  },
  {
    id: "a6.toggleGrid",
    label: "Toggle A6 Grid (G)",
    description: "Toggle A6 layout grid overlay",
    category: "A6 Studio",
    defaultShortcut: "G",
    scope: "a6-studio",
    priority: 15,
    icon: "Grid",
    keywords: ["a6 grid"],
  },
  {
    id: "a6.toggleGuides",
    label: "Toggle Cutting Guides (T)",
    description: "Toggle printed cutting marks and 74×105mm boundaries",
    category: "A6 Studio",
    defaultShortcut: "T",
    scope: "a6-studio",
    priority: 15,
    icon: "Scissors",
    keywords: ["a6 cutting guides"],
  },
  {
    id: "a6.resetAll",
    label: "Reset A6 Adjustments",
    description: "Reset zoom, position, and filter values for active A6 card",
    category: "A6 Studio",
    defaultShortcut: "Ctrl+Shift+R",
    alternativeShortcuts: ["Cmd+Shift+R"],
    scope: "a6-studio",
    priority: 15,
    icon: "RefreshCw",
    keywords: ["reset a6 adjustments"],
  },
  {
    id: "a6.print",
    label: "Print A6 Layout (Ctrl+P)",
    description: "Send A6 sheet to physical printer",
    category: "A6 Studio",
    defaultShortcut: "Ctrl+P",
    alternativeShortcuts: ["Cmd+P"],
    scope: "a6-studio",
    priority: 15,
    icon: "Printer",
    keywords: ["print a6"],
  },
  {
    id: "a6.export",
    label: "Export A6 Layout PDF (Ctrl+E)",
    description: "Export high-resolution PDF of A6 layout",
    category: "A6 Studio",
    defaultShortcut: "Ctrl+E",
    alternativeShortcuts: ["Cmd+E"],
    scope: "a6-studio",
    priority: 15,
    icon: "Download",
    keywords: ["export a6"],
  },
  {
    id: "a6.close",
    label: "Close A6 Studio (Escape)",
    description: "Exit A6 Half-Card Studio workspace",
    category: "A6 Studio",
    defaultShortcut: "Escape",
    scope: "a6-studio",
    priority: 15,
    allowInInputs: true,
    icon: "X",
    keywords: ["close a6 studio"],
  },
];
